# Generated by Django 5.2.16 on 2026-07-27 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название формы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликована'), ('CLOSED', 'Сбор ответов закрыт'), ('ARCHIVED', 'Архивная')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('allow_multiple_submissions', models.BooleanField(default=False, verbose_name='Разрешать повторное заполнение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('code', models.CharField(blank=True, choices=[('APPEARANCE', 'Внешний вид'), ('COLOR', 'Цвет'), ('CONSISTENCY', 'Консистенция'), ('SMELL', 'Запах'), ('TASTE', 'Вкус'), ('COMMENT', 'Комментарии к балловым оценкам')], max_length=30, verbose_name='Системный код')),
                ('question_type', models.CharField(choices=[('RATING', 'Балловая оценка'), ('TEXT', 'Текстовый комментарий')], default='RATING', max_length=20, verbose_name='Тип вопроса')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=1, default='1.0', max_digits=2, null=True, verbose_name='Минимальная оценка')),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=1, default='5.0', max_digits=2, null=True, verbose_name='Максимальная оценка')),
                ('decimal_places', models.PositiveSmallIntegerField(default=1, verbose_name='Количество знаков после запятой')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название образца')),
                ('description', models.TextField(blank=True, verbose_name='Характеристика образца')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='surveys.survey', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['owner', 'status'], name='survey_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='unique_question_order_per_survey'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('survey', 'code'), name='unique_question_code_per_survey'),
        ),
        migrations.AddConstraint(
            model_name='surveysample',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='unique_sample_order_per_survey'),
        ),
    ]
