# Generated by Django 5.2.16 on 2026-07-28 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор ответа')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заполнения')),
                ('is_excluded', models.BooleanField(db_index=True, default=False, verbose_name='Исключён из расчётов')),
                ('exclusion_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина исключения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='Браузер')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.survey', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Ответ участника',
                'verbose_name_plural': 'Ответы участников',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Числовая оценка')),
                ('text_value', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.surveyquestion', verbose_name='Вопрос')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.surveysample', verbose_name='Образец')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.submission', verbose_name='Заполнение')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['sample__order', 'question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['survey', 'is_excluded'], name='submission_survey_excl_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['sample', 'question'], name='answer_sample_question_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'sample', 'question'), name='unique_answer_per_sample_question'),
        ),
    ]
