# Generated by Django 5.2.16 on 2026-07-28 11:39

import apps.surveys.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_submission_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(blank=True, default='КК-Ф-020', max_length=100, verbose_name='Код документа')),
                ('protocol_number', models.CharField(blank=True, max_length=50, verbose_name='Номер протокола')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата протокола')),
                ('responsible_employee', models.CharField(blank=True, max_length=255, verbose_name='Сотрудник отдела разработки продуктов')),
                ('tasting_goal', models.TextField(blank=True, verbose_name='Цель дегустации')),
                ('room_conditions', models.TextField(blank=True, default='Температура воздуха в помещении: +18 – +25 °С, относительная влажность воздуха – менее 75%.', verbose_name='Условия в помещении')),
                ('product_conditions', models.TextField(blank=True, verbose_name='Температура и условия продуктов')),
                ('conclusion', models.TextField(blank=True, verbose_name='Заключение')),
                ('signer_position', models.CharField(blank=True, default='Нач. ОРП', max_length=255, verbose_name='Должность подписанта')),
                ('signer_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО подписанта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='surveys.survey', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Реквизиты протокола',
                'verbose_name_plural': 'Реквизиты протоколов',
            },
        ),
        migrations.CreateModel(
            name='GeneratedProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(max_length=50, verbose_name='Номер протокола')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('file', models.FileField(upload_to=apps.surveys.models.protocol_upload_to, verbose_name='Файл DOCX')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Сформировал')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_protocols', to='surveys.survey', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Сформированный протокол',
                'verbose_name_plural': 'Сформированные протоколы',
                'ordering': ['-version', '-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('survey', 'version'), name='unique_protocol_version_per_survey')],
            },
        ),
    ]
