# Generated by Django 5.2.16 on 2026-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveyprotocol_generatedprotocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyprotocol',
            name='responsible_department',
            field=models.CharField(default='разработки продуктов', max_length=255, verbose_name='Отдел сотрудника'),
        ),
        migrations.AlterField(
            model_name='surveyprotocol',
            name='responsible_employee',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО сотрудника'),
        ),
    ]
