from django.urls import path

from . import views


app_name = "surveys"


urlpatterns = [
    path(
        "public/<uuid:public_id>/",
        views.public_survey,
        name="public_survey",
    ),
    path(
        (
            "public/<uuid:public_id>/"
            "success/<uuid:submission_id>/"
        ),
        views.public_survey_success,
        name="public_survey_success",
    ),
    path(
        "",
        views.survey_list,
        name="survey_list",
    ),
    path(
        "create/",
        views.survey_create,
        name="survey_create",
    ),
    path(
        "<int:survey_id>/edit/",
        views.survey_edit,
        name="survey_edit",
    ),
    path(
        "<int:survey_id>/copy/",
        views.survey_copy,
        name="survey_copy",
    ),
    path(
        "<int:survey_id>/publish/",
        views.survey_publish,
        name="survey_publish",
    ),
    path(
        "<int:survey_id>/close/",
        views.survey_close,
        name="survey_close",
    ),
    path(
        "<int:survey_id>/archive/",
        views.survey_archive,
        name="survey_archive",
    ),
    path(
        "<int:survey_id>/samples/create/",
        views.sample_create,
        name="sample_create",
    ),
    path(
        (
            "<int:survey_id>/samples/"
            "<int:sample_id>/edit/"
        ),
        views.sample_edit,
        name="sample_edit",
    ),
    path(
        (
            "<int:survey_id>/samples/"
            "<int:sample_id>/delete/"
        ),
        views.sample_delete,
        name="sample_delete",
    ),
    path(
        (
            "<int:survey_id>/samples/"
            "<int:sample_id>/move-up/"
        ),
        views.sample_move_up,
        name="sample_move_up",
    ),
    path(
        (
            "<int:survey_id>/samples/"
            "<int:sample_id>/move-down/"
        ),
        views.sample_move_down,
        name="sample_move_down",
    ),
    path(
        "<int:survey_id>/results/",
        views.survey_results,
        name="survey_results",
    ),
    path(
        "<int:survey_id>/qr/",
        views.survey_qr_code,
        name="survey_qr_code",
    ),
    path(
        "<int:survey_id>/qr/download/",
        views.survey_qr_code_download,
        name="survey_qr_code_download",
    ),
    path(
        "<int:survey_id>/qr/print/",
        views.survey_qr_print,
        name="survey_qr_print",
    ),
    path(
        "<int:survey_id>/export/excel/",
        views.survey_excel_export,
        name="survey_excel_export",
    ),
    path(
        (
            "<int:survey_id>/submissions/"
            "<int:submission_id>/"
        ),
        views.submission_detail,
        name="submission_detail",
    ),
    path(
        (
            "<int:survey_id>/submissions/"
            "<int:submission_id>/exclude/"
        ),
        views.submission_exclude,
        name="submission_exclude",
    ),
    path(
        (
            "<int:survey_id>/submissions/"
            "<int:submission_id>/include/"
        ),
        views.submission_include,
        name="submission_include",
    ),
    path(
        "<int:survey_id>/protocol/",
        views.survey_protocol_edit,
        name="survey_protocol_edit",
    ),
    path(
        "<int:survey_id>/protocol/generate/",
        views.survey_protocol_generate,
        name="survey_protocol_generate",
    ),
    path(
        (
            "<int:survey_id>/protocols/"
            "<int:protocol_id>/download/"
        ),
        views.generated_protocol_download,
        name="generated_protocol_download",
    ),
]